fixing AppImage so it can fetch json data from the internet with idna encoding
user@disp8039:~$ dist/buskill.AppImage -U
buskill version {'GITHUB_REF': 'refs/heads/dev', 'GITHUB_SHA': '2c9bc8b35dcd56589e39e554ff131ced3a6adb32', 'SOURCE_DATE_EPOCH': '1597694454'}
DEBUG: Unable to write to '/tmp/.mount_buskilX0Iduz/opt/src'; skipping.
DEBUG: using DATA_DIR:|/home/user/dist/.buskill|
Traceback (most recent call last):
  File "/tmp/.mount_buskilX0Iduz/opt/src/main.py", line 103, in <module>
    ret = BusKillCLI()
  File "/tmp/.mount_buskilX0Iduz/opt/src/buskill_cli.py", line 84, in BusKillCLI
    buskill.upgrade()
  File "/tmp/.mount_buskilX0Iduz/opt/src/buskill.py", line 478, in upgrade
    with urllib.request.urlopen( "https://api.github.com/repos/buskill/buskill-app/releases/latest", cafile=certifi.where() ) as url:
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 1424, in connect
    super().connect()
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/http/client.py", line 940, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/tmp/.mount_buskilX0Iduz/opt/python3.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
LookupError: unknown encoding: idna
user@disp8039:~$