the last commit's build was fully functional in windows!
Unfortunately, it broke linux with the following error message:

  user@user:~/Downloads/buskill-linux-x86_64.149828814/dist$ ./buskill.AppImage
  buskill version 0.1
  No command-line arguments detected. Launching GUI
  Hint: execute `buskill --help` for command-line usage
  Traceback (most recent call last):
    File "/tmp/.mount_buskila3jY3D/opt/src/main.py", line 71, in <module>
      from buskill_gui import *
    File "/tmp/.mount_buskila3jY3D/opt/src/buskill_gui.py", line 16, in <module>
      import buskill
    File "/tmp/.mount_buskila3jY3D/opt/src/buskill.py", line 61, in <module>
      WORD = c_ushort
  NameError: name 'c_ushort' is not defined

I'm attempting to fix this issue with this commit by wrapping the windows constant declarations in a conditional that will only declare them on windows machines