fixing path to upgraded_from on deletion
The last build works great. The upgrade works. The restart works. The deletion of the old version works after restart. But it crashes after that because the path to 'upgraded_from.py' is wrong.

This commit should fix that path.

called upgrade3_tick()
INFO: Installed new version executable to  '/home/user/Downloads/buskill-lin-v0.3.0-x86_64/buskill-v0.3.0.AppImage
 [INFO/Process-1] process shutting down
 [DEBUG/Process-1] running all "atexit" finalizers with priority >= 0
 [DEBUG/Process-1] running the remaining "atexit" finalizers
 [INFO/Process-1] process exiting with exitcode 0
called upgrade3_tick()
DEBUG: Exiting and launching /home/user/Downloads/buskill-lin-v0.3.0-x86_64/buskill-v0.3.0.AppImage
buskill version {'VERSION': 'v0.3.0', 'GITHUB_REF': 'refs/heads/v0.3.0', 'GITHUB_SHA': '2bbfa156a1a5fae4010acbdbe1c308fc6728b31f', 'SOURCE_DATE_EPOCH': '1601882288'}
No command-line arguments detected. Launching GUI
Hint: execute `buskill --help` for command-line usage
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_20-10-05_9.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/tmp/.mount_buskilJaih88/opt/python3.7/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.8 (default, Jul  4 2020, 10:00:57)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
[INFO   ] [Python      ] Interpreter at "/home/user/Downloads/buskill-lin-v0.3.0-x86_64/buskill-v0.3.0.AppImage"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 18.3.6'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'llvmpipe (LLVM 7.0, 256 bits)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
DEBUG: EXE_PATH:|/home/user/Downloads/buskill-lin-v0.3.0-x86_64/buskill-v0.3.0.AppImage|
DEBUG: EXE_DIR:|/home/user/Downloads/buskill-lin-v0.3.0-x86_64|
DEBUG: EXE_FILE:|buskill-v0.3.0.AppImage|
DEBUG: APP_DIR:|/home/user/Downloads/buskill-lin-v0.3.0-x86_64|
DEBUG: APPS_DIR:|/home/user/Downloads|
DEBUG: os.environ['PATH']:|/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/user/Downloads/buskill-lin-v0.2.1-x86_64:/home/user/Downloads/buskill-lin-v0.2.1-x86_64:/home/user/Downloads/buskill-lin-v0.3.0-x86_64:/home/user/Downloads/buskill-lin-v0.3.0-x86_64|

INFO: using DATA_DIR:|/home/user/Downloads/.buskill|
DEBUG: Detected first-run of new version. Deleting old version.
	{'APP_DIR': '/home/user/Downloads/buskill-lin-v0.2.1-x86_64'}

 Traceback (most recent call last):
   File "/tmp/.mount_buskilJaih88/opt/src/main.py", line 97, in <module>
     from buskill_gui import BusKillApp
   File "/tmp/.mount_buskilJaih88/opt/src/buskill_gui.py", line 337, in <module>
     class BusKillApp(App):
   File "/tmp/.mount_buskilJaih88/opt/src/buskill_gui.py", line 346, in BusKillApp
     bk = packages.buskill.BusKill()
   File "/tmp/.mount_buskilJaih88/opt/src/packages/buskill/__init__.py", line 323, in __init__
     self.handle_upgrades()
   File "/tmp/.mount_buskilJaih88/opt/src/packages/buskill/__init__.py", line 410, in handle_upgrades
     os.unlink( 'upgraded_from.py' )
 FileNotFoundError: [Errno 2] No such file or directory: 'upgraded_from.py'
 [INFO/MainProcess] process shutting down
 [DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
 [DEBUG/MainProcess] running the remaining "atexit" finalizers
user@disp9121:~/Downloads$