replacing os.getlogin() with getpass.getuser()
This commit replaces the function called where we log the username of
the execution user at the very start of the application, for debug
purposes.

os.getlogin() worked most of the time, but sometimes it would cause a
fatal crash

  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  OSError: [Errno 6] No such device or address

The official python docs literally say to just use getpass.getuser()
instead

 * https://docs.python.org/3/library/os.html#os.getlogin
 * https://docs.python.org/3/library/getpass.html#getpass.getuser

Note that this could be a security vulnerability, because
getpass.getlogin() just checks the environment variables -- which the
user can trivially change. We don't use it for auth tho, just logging,
so it's safe for use in this way.

For more info, see this ticket:

 * https://github.com/BusKill/buskill-app/issues/120