brew says that the --build-bottle arg doesn't exist
  Error: invalid option: --build-bottle

I guess that's another error in kivy's documentation

 * https://kivy.org/doc/stable/guide/packaging-osx.html