trying to return a tuple with __reduce__()
Well the last build fails because dill isn't installed, but if I execute main.py with a python that I've installed the dill module to, then I get an infinite recursion error.

I'm still learning how to use __reduce__(). This commit tries to return a dumb string in a tuple, but the first item of the tuple may very well need to be a type. We'll see..

maltfield@5129 Downloads % python3 buskill-1599822203.app/Contents/MacOS/main.py
...
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 446, in dump
     StockPickler.dump(self, obj)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 437, in dump
     self.save(obj)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 524, in save
     rv = reduce(self.proto)
   File "/Users/maltfield/Downloads/buskill-1599822203.app/Contents/MacOS/packages/buskill/__init__.py", line 153, in __reduce__
     return dill.dumps(self)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 265, in dumps
     dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 259, in dump
     Pickler(file, protocol, **_kwds).dump(obj)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 446, in dump
     StockPickler.dump(self, obj)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 437, in dump
     self.save(obj)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 524, in save
     rv = reduce(self.proto)
   File "/Users/maltfield/Downloads/buskill-1599822203.app/Contents/MacOS/packages/buskill/__init__.py", line 153, in __reduce__
     return dill.dumps(self)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 265, in dumps
     dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
   File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dill/_dill.py", line 255, in dump
     from .settings import settings
   File "<frozen importlib._bootstrap>", line 420, in parent
 RecursionError: maximum recursion depth exceeded while calling a Python object
 [INFO/MainProcess] process shutting down
 [DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
 [DEBUG/MainProcess] running the remaining "atexit" finalizers
maltfield@5129 Downloads %