moved windows helper functions (most importantly the classes) outsdie the main BusKill class so that they can reference each other, because inner classes can't reference each other in python
   AttributeError: 'Notification' object has no attribute 'DEV_BROADCAST_HDR'