changing pyinstaller icon from png to ico for windows
I think it's failing to build because it's interpreting the 'buskill-icon-150.png' as 'buskill-icon-150.png.exe'

2020-10-04T14:44:01.0308630Z 19403 INFO: Building EXE from EXE-00.toc
2020-10-04T14:44:01.0321652Z 19404 INFO: Copying icons from .\..\src\images\buskill-icon-150.png
2020-10-04T14:44:01.0324851Z  Traceback (most recent call last):
2020-10-04T14:44:01.0325375Z 19405 WARNING: stderr: Traceback (most recent call last):
2020-10-04T14:44:01.0326078Z    File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
2020-10-04T14:44:01.0326912Z 19405 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
2020-10-04T14:44:01.0328322Z      yield
2020-10-04T14:44:01.0328713Z 19405 WARNING: stderr:     yield
2020-10-04T14:44:01.0329338Z    File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
2020-10-04T14:44:01.0330356Z 19405 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
2020-10-04T14:44:01.0332109Z      return _dll._LoadLibraryEx(fileName, 0, flags)
2020-10-04T14:44:01.0332744Z 19405 WARNING: stderr:     return _dll._LoadLibraryEx(fileName, 0, flags)
2020-10-04T14:44:01.0334235Z    File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
2020-10-04T14:44:01.0335288Z 19406 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
2020-10-04T14:44:01.0335983Z      raise make_error(function, function_name)
2020-10-04T14:44:01.0336519Z 19406 WARNING: stderr:     raise make_error(function, function_name)
2020-10-04T14:44:01.0337106Z  OSError: [WinError 193] %1 is not a valid Win32 application.
2020-10-04T14:44:01.0337711Z 19406 WARNING: stderr: OSError: [WinError 193] %1 is not a valid Win32 application.
2020-10-04T14:44:01.0338310Z
2020-10-04T14:44:01.0338610Z 19406 WARNING: stderr:
2020-10-04T14:44:01.0339125Z  During handling of the above exception, another exception occurred:
2020-10-04T14:44:01.0339793Z 19406 WARNING: stderr: During handling of the above exception, another exception occurred:
2020-10-04T14:44:01.0340450Z
2020-10-04T14:44:01.0340757Z 19406 WARNING: stderr:
2020-10-04T14:44:01.0346975Z  Traceback (most recent call last):
2020-10-04T14:44:01.0347558Z 19406 WARNING: stderr: Traceback (most recent call last):
2020-10-04T14:44:01.0348283Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 233, in CopyIcons
2020-10-04T14:44:01.0349113Z 19406 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 233, in CopyIcons
2020-10-04T14:44:01.0349875Z      hsrc = win32api.LoadLibraryEx(srcpath, 0, LOAD_LIBRARY_AS_DATAFILE)
2020-10-04T14:44:01.0350943Z 19407 WARNING: stderr:     hsrc = win32api.LoadLibraryEx(srcpath, 0, LOAD_LIBRARY_AS_DATAFILE)
2020-10-04T14:44:01.0351761Z    File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
2020-10-04T14:44:01.0352582Z 19407 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
2020-10-04T14:44:01.0353653Z      return _dll._LoadLibraryEx(fileName, 0, flags)
2020-10-04T14:44:01.0354518Z 19407 WARNING: stderr:     return _dll._LoadLibraryEx(fileName, 0, flags)
2020-10-04T14:44:01.0355270Z    File "C:\tmp\python\lib\contextlib.py", line 130, in __exit__
2020-10-04T14:44:01.0355953Z 19407 WARNING: stderr:   File "C:\tmp\python\lib\contextlib.py", line 130, in __exit__
2020-10-04T14:44:01.0356761Z      self.gen.throw(type, value, traceback)
2020-10-04T14:44:01.0357531Z 19407 WARNING: stderr:     self.gen.throw(type, value, traceback)
2020-10-04T14:44:01.0359030Z    File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
2020-10-04T14:44:01.0359815Z 19407 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
2020-10-04T14:44:01.0360632Z      raise error(exception.winerror, exception.function, exception.strerror)
2020-10-04T14:44:01.0361653Z 19408 WARNING: stderr:     raise error(exception.winerror, exception.function, exception.strerror)
2020-10-04T14:44:01.0362887Z  win32ctypes.pywin32.pywintypes.error: (193, 'LoadLibraryExW', '%1 is not a valid Win32 application.')
2020-10-04T14:44:01.0364024Z 19408 WARNING: stderr: win32ctypes.pywin32.pywintypes.error: (193, 'LoadLibraryExW', '%1 is not a valid Win32 application.')
2020-10-04T14:44:01.0364720Z
2020-10-04T14:44:01.0365012Z 19408 WARNING: stderr:
2020-10-04T14:44:01.0365481Z  During handling of the above exception, another exception occurred:
2020-10-04T14:44:01.0366275Z 19408 WARNING: stderr: During handling of the above exception, another exception occurred:
2020-10-04T14:44:01.0366723Z
2020-10-04T14:44:01.0367002Z 19408 WARNING: stderr:
2020-10-04T14:44:01.0367355Z  Traceback (most recent call last):
2020-10-04T14:44:01.0367786Z 19408 WARNING: stderr: Traceback (most recent call last):
2020-10-04T14:44:01.0368258Z    File "C:\tmp\python\lib\runpy.py", line 193, in _run_module_as_main
2020-10-04T14:44:01.0369238Z 19408 WARNING: stderr:   File "C:\tmp\python\lib\runpy.py", line 193, in _run_module_as_main
2020-10-04T14:44:01.0369767Z      "__main__", mod_spec)
2020-10-04T14:44:01.0370110Z 19409 WARNING: stderr:     "__main__", mod_spec)
2020-10-04T14:44:01.0370743Z    File "C:\tmp\python\lib\runpy.py", line 85, in _run_code
2020-10-04T14:44:01.0371379Z 19409 WARNING: stderr:   File "C:\tmp\python\lib\runpy.py", line 85, in _run_code
2020-10-04T14:44:01.0371819Z      exec(code, run_globals)
2020-10-04T14:44:01.0372566Z 19409 WARNING: stderr:     exec(code, run_globals)
2020-10-04T14:44:01.0373143Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
2020-10-04T14:44:01.0374087Z 19409 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
2020-10-04T14:44:01.0374821Z      run()
2020-10-04T14:44:01.0375166Z 19409 WARNING: stderr:     run()
2020-10-04T14:44:01.0375699Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 114, in run
2020-10-04T14:44:01.0376597Z 19409 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 114, in run
2020-10-04T14:44:01.0377604Z      run_build(pyi_config, spec_file, **vars(args))
2020-10-04T14:44:01.0378489Z 19410 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
2020-10-04T14:44:01.0379284Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
2020-10-04T14:44:01.0380220Z 19410 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
2020-10-04T14:44:01.0381636Z      PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
2020-10-04T14:44:01.0382682Z 19410 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
2020-10-04T14:44:01.0383847Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
2020-10-04T14:44:01.0384738Z 19410 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
2020-10-04T14:44:01.0385441Z      build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
2020-10-04T14:44:01.0386054Z 19411 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
2020-10-04T14:44:01.0386715Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
2020-10-04T14:44:01.0387433Z 19411 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
2020-10-04T14:44:01.0388198Z      exec(code, spec_namespace)
2020-10-04T14:44:01.0388619Z 19411 WARNING: stderr:     exec(code, spec_namespace)
2020-10-04T14:44:01.0390747Z    File ".\buskill.spec", line 46, in <module>
2020-10-04T14:44:01.0391571Z 19411 WARNING: stderr:   File ".\buskill.spec", line 46, in <module>
2020-10-04T14:44:01.0394365Z      console=True )
2020-10-04T14:44:01.0395209Z 19412 WARNING: stderr:     console=True )
2020-10-04T14:44:01.0396073Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\api.py", line 446, in __init__
2020-10-04T14:44:01.0397419Z 19412 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\api.py", line 446, in __init__
2020-10-04T14:44:01.0404400Z      self.__postinit__()
2020-10-04T14:44:01.0405208Z 19412 WARNING: stderr:     self.__postinit__()
2020-10-04T14:44:01.0406040Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
2020-10-04T14:44:01.0407398Z 19413 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
2020-10-04T14:44:01.0409118Z      self.assemble()
2020-10-04T14:44:01.0409712Z 19413 WARNING: stderr:     self.assemble()
2020-10-04T14:44:01.0410479Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\api.py", line 540, in assemble
2020-10-04T14:44:01.0412506Z 19413 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\building\api.py", line 540, in assemble
2020-10-04T14:44:01.0415040Z      icon.CopyIcons(tmpnm, self.icon)
2020-10-04T14:44:01.0415699Z 19414 WARNING: stderr:     icon.CopyIcons(tmpnm, self.icon)
2020-10-04T14:44:01.0416819Z    File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 234, in CopyIcons
2020-10-04T14:44:01.0418014Z 19414 WARNING: stderr:   File "C:\tmp\kivy_venv\lib\site-packages\PyInstaller\utils\win32\icon.py", line 234, in CopyIcons
2020-10-04T14:44:01.0420302Z      except win32api.error as W32E:
2020-10-04T14:44:01.0424391Z 19414 WARNING: stderr:     except win32api.error as W32E:
2020-10-04T14:44:01.0425433Z  AttributeError: module 'win32ctypes.pywin32.win32api' has no attribute 'error'
2020-10-04T14:44:01.0426376Z 19414 WARNING: stderr: AttributeError: module 'win32ctypes.pywin32.win32api' has no attribute 'error'
2020-10-04T14:44:01.1529769Z
2020-10-04T14:44:01.1536457Z DEBUG:  274+  >>>> cd .. | Out-String
2020-10-04T14:44:01.1545121Z