attempting to pass the buskill object to the Notification object so that the Notification methods can call buskill menthods, namely windows-specific triggers that should live in the buskill class
   AttributeError: 'Notification' object has no attribute 'triggerWin'