forgot it's a method of 'self'
  DEBUG: Attempting to set 'trigger' set to 'soft-shutdown'
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
  NameError: name 'spawn_root_child' is not defined
  [1118] Failed to execute script 'main' due to unhandled exception: name 'spawn_root_child' is not defined
  [1118] Traceback:
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
      spawn_root_child()
  NameError: name 'spawn_root_child' is not defined