testing if I can get the exception without trying to catch it
I was able to isolate the traceback of the issue

INFO: BusKill is disarmed.
> /Users/maltfield/Downloads/packages/buskill/__init__.py(641)upgrade_bg()
(Pdb) c [DEBUG/MainProcess] created semlock with handle 27
 [DEBUG/MainProcess] created semlock with handle 28
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 22, in <module>
     import platform, os
   File "kivy/app.py", line 855, in run
   File "kivy/base.py", line 504, in runTouchApp
   File "kivy/core/window/window_sdl2.py", line 747, in mainloop
   File "kivy/core/window/window_sdl2.py", line 479, in _mainloop
   File "kivy/base.py", line 342, in idle
   File "kivy/base.py", line 327, in dispatch_input
   File "kivy/base.py", line 293, in post_dispatch_input
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "kivy/uix/behaviors/button.py", line 179, in on_touch_up
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "kivy/lang/builder.py", line 64, in custom_callback
   File "/Users/maltfield/Downloads/buskill-1599562887.app/Contents/MacOS/buskill.kv", line 190, in <module>
     on_release: root.continue_function()
   File "buskill_gui.py", line 154, in update2
     self.bk.upgrade_bg()
   File "packages/buskill/__init__.py", line 641, in upgrade_bg
   File "multiprocessing/process.py", line 112, in start
   File "multiprocessing/context.py", line 223, in _Popen
   File "multiprocessing/context.py", line 284, in _Popen
   File "multiprocessing/popen_spawn_posix.py", line 32, in __init__

File "site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 82, in __init__
   File "multiprocessing/popen_fork.py", line 20, in __init__
   File "multiprocessing/popen_spawn_posix.py", line 47, in _launch
   File "multiprocessing/reduction.py", line 60, in dump
 TypeError: can't pickle weakref objects
[981] Failed to execute script main
 [INFO/MainProcess] process shutting down
 [DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
 [DEBUG/MainProcess] running the remaining "atexit" finalizers
bash-3.2$

So the error "TypeError: can't pickle weakref objects" occurs in reduction.py's dump() function, which uses the class = ForkingPickler.

I found this bug report for the same issue, which was apparently new to python 3.7.0 and it says that the cause is trying to pickle the Process() object. Well, I'm not intentionally trying to pickle *any* object. All I want is to be able to fucking catch exceptions from a child process and pass them to the UI!

 * https://bugs.python.org/issue34034

Maybe I can override this ForkingPickler somehow so that it sends back a blank dict() that's been pickled instead of the object it wants to fix this somehow??