a few fixes as I work out the release process
     * I was missing a '-y' in the apt-get install of the linux build script. I'm surprised it was working at all on GitHub's shared runners (?). The last build's hash actually didn't match. I'll have to do a diffoscope again *sigh*
     * The docutils-style comments in buskill.kv actually totally broke its execution, and it didn't work for autodoc in sphinx anyway, so I'm reverting it back to good-ol hash-style flowerbox comments

    root@disp215:~/dist# squashfs-root/AppRun
    buskill version {'GITHUB_REF': 'refs/heads/master', 'GITHUB_SHA': 'ab223f3fc48cb2581e4095d9c7fc74ed7b0c48dc', 'SOURCE_DATE_EPOCH': '1595605668'}
    No command-line arguments detected. Launching GUI
    Hint: execute `buskill --help` for command-line usage
    [INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_20-07-29_1.txt
    [INFO   ] [Kivy        ] v1.11.1
    [INFO   ] [Kivy        ] Installed at "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/__init__.py"
    [INFO   ] [Python      ] v3.7.8 (default, Jul  4 2020, 10:00:57)
    [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
    [INFO   ] [Python      ] Interpreter at "/root/dist/squashfs-root/opt/python3.7/bin/python3.7 /root/dist/squashfs-root/opt/src/main.py"
    [INFO   ] [Factory     ] 184 symbols loaded
    [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
    [INFO   ] [Text        ] Provider: sdl2
    [INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
    [INFO   ] [GL          ] Using the "OpenGL" graphics system
    [INFO   ] [GL          ] Backend used <sdl2>
    [INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 18.3.6'>
    [INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
    [INFO   ] [GL          ] OpenGL renderer <b'llvmpipe (LLVM 7.0, 256 bits)'>
    [INFO   ] [GL          ] OpenGL parsed version: 3, 1
    [INFO   ] [GL          ] Shading version <b'1.40'>
    [INFO   ] [GL          ] Texture max size <8192>
    [INFO   ] [GL          ] Texture max units <32>
    [INFO   ] [Window      ] auto add sdl2 input provider
    [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
     Traceback (most recent call last):
       File "/root/dist/squashfs-root/opt/src/main.py", line 97, in <module>
         BusKill().run()
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/app.py", line 828, in run
         self.load_kv(filename=self.kv_file)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/app.py", line 599, in load_kv
         root = Builder.load_file(rfilename)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/lang/builder.py", line 301, in load_file
         return self.load_string(data, **kwargs)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/lang/builder.py", line 368, in load_string
         parser = Parser(content=string, filename=fn)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/lang/parser.py", line 401, in __init__
         self.parse(content)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/lang/parser.py", line 510, in parse
         objects, remaining_lines = self.parse_level(0, lines)
       File "/root/dist/squashfs-root/opt/python3.7/lib/python3.7/site-packages/kivy/lang/parser.py", line 580, in parse_level
         raise ParserException(self, ln, 'Identifier missing')
     kivy.lang.parser.ParserException: Parser: File "/root/dist/squashfs-root/opt/src/buskill.kv", line 2:
     ...
           1:"""
     >>    2:::
           3:
           4:  File:    buskill.kv
     ...
     Identifier missing
    root@disp215:~/dist#