actually add message to write()
  Traceback (most recent call last):
    File "buskill/root_child_mac.py", line 85, in <module>
  TypeError: write() takes exactly one argument (0 given)
  [60044] Failed to execute script 'root_child_mac' due to unhandled exception: write() takes exactly one argument (0 given)
  [60044] Traceback:
  (null)