the last build works for linux (it downloads the latest release and uses gnupg to verify its signature)
	user@disp8039:~$ dist/buskill.AppImage -U
	buskill version {'GITHUB_REF': 'refs/heads/dev', 'GITHUB_SHA': '34e74f873fac5a76facf49739e0db099e10d0a64', 'SOURCE_DATE_EPOCH': '1597695200'}
	DEBUG: Unable to write to '/tmp/.mount_buskilZryRJk/opt/src'; skipping.
	DEBUG: using DATA_DIR:|/home/user/dist/.buskill|
	{'GyGyEE8N0jQbR9ZIIgWKwVBS7sQ': {'creation_date': '2020-08-01', 'timestamp': '1596270032', 'keyid': '68B8BCB0C5023905', 'username': 'BusKill Releases Signing Key 2020.07 <releases@buskill.in>', 'status': 'signature valid', 'fingerprint': '798DC1101F3DEC428ADE124D68B8BCB0C5023905', 'expiry': '0', 'pubkey_fingerprint': 'E0AFFF57DC00FBE0563587614AE21E1936CE786A', 'trust_level': 0, 'trust_text': 'TRUST_UNDEFINED'}}
	user@disp8039:~$

But it does not work for MacOS, which I'm attempting to fix with this commit

	maltfield@5129 ~ % /Volumes/buskill/buskill.app/Contents/MacOS/buskill -U
	buskill version {'GITHUB_REF': 'refs/heads/dev', 'GITHUB_SHA': '34e74f873fac5a76facf49739e0db099e10d0a64', 'SOURCE_DATE_EPOCH': '1597695200'}
	Traceback (most recent call last):
  	File "main.py", line 102, in <module>
    	from buskill_cli import *
  	File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    	exec(bytecode, module.__dict__)
  File "buskill_cli.py", line 20, in <module>
    	import buskill
  	File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    	exec(bytecode, module.__dict__)
  File "buskill.py", line 21, in <module>
    	import urllib.request, json, certifi, sys, os, shutil, tempfile, gnupg
	ModuleNotFoundError: No module named 'gnupg'
	[23322] Failed to execute script main
	maltfield@5129 ~ %

Note that, as the TODO states, installing from pip is just a fast short-hand now and we'll actually do the gpg sig verification (or 3TOFU & download/pin) for the actual release before moved from dev to master