fixing missing self in armWin() after converting to buskill.py to object
The last commit's windows build worked, and I confirmed that its upgrade UX is perfect in the GUI. Only clicking the "arm" button fails with this

   TypeError: armWin() takes 0 positional arguments but 1 was given