s/gud/gid/ (typo)
  DEBUG: Attempting to set 'trigger' set to 'soft-shutdown'
  DEBUG: Called spawn_root_child()
  DEBUG: No root_child detected. Attempting to spawn one.
  DEBUG: root_child_path:|/Volumes/buskill-cli-shutdown-trigger/buskill-cli-shutdown-trigger.app/Contents/MacOS/packages/buskill/root_child_mac.py|
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
    File "packages/buskill/__init__.py", line 603, in spawn_root_child
  AttributeError: 'os.stat_result' object has no attribute 'st_gud'
  [1154] Failed to execute script 'main' due to unhandled exception: 'os.stat_result' object has no attribute 'st_gud'
  [1154] Traceback:
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
      self.spawn_root_child()
    File "packages/buskill/__init__.py", line 603, in spawn_root_child
      group = os.stat(root_child_path).st_gud
  AttributeError: 'os.stat_result' object has no attribute 'st_gud'