we must make the root child instance field a dictionary before we can assign io to it
  DEBUG: root_child_path:|/Volumes/buskill-cli-shutdown-trigger/buskill-cli-shutdown-trigger.app/Contents/MacOS/packages/buskill/root_child_mac.py|
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
    File "packages/buskill/__init__.py", line 646, in spawn_root_child
  TypeError: 'NoneType' object does not support item assignment
  [3889] Failed to execute script 'main' due to unhandled exception: 'NoneType' object does not support item assignment
  [3889] Traceback:
  Traceback (most recent call last):
    File "main.py", line 142, in <module>
      ret = BusKillCLI()
    File "buskill_cli.py", line 147, in BusKillCLI
      bk.set_trigger( args.trigger )
    File "packages/buskill/__init__.py", line 541, in set_trigger
      self.spawn_root_child()
    File "packages/buskill/__init__.py", line 646, in spawn_root_child
      self.root_child['io'] = ctypes.c_void_p()
  TypeError: 'NoneType' object does not support item assignment